### ISSUE TITLE
The agent ip address shouldn't be the one that stalkerweb sees

### ISSUE THREAD

**Issue by omame** [pandemicsyn/stalker#43]
When an agent register itself with stalkerweb the ip address that makes it to the hosts db is the one that stalkerweb sees the connection coming from (see [here](https://github.com/pandemicsyn/stalker/blob/master/stalkerweb/views.py#L132)).
This can cause problems when the agent has more ip addresses to choose from and tries to enforce a different one in the config file. As a result the agent listens on one ip and gets registered with another, resulting in an immediate host unreachable.

**Comment by pandemicsyn** [comment]
Yeah your totally right. I could have sworn I added an override when we added the listen_addr directive to the agent that would allow the agent to specify what ip to use. I guess I forgot. I'll get it added in this week.
