### ISSUE TITLE
notification priorities across backends

### ISSUE THREAD

**Issue by andrew-hale** [pandemicsyn/stalker#56]
pull #39 added a load of extra service keys to PagerDuty notification method but skipped them on GenericHTTP making switching hard. 
Would be nice if go version doesn't include this oversight.

**Comment by pandemicsyn** [comment]
You just want the GenericHTTP hook plugin to support multiple service keys right ? The Go Version just has PagerDuty, Twilio, and Mailgun. I can definitely add the generic http call if you think you guys might use it in the future.
